### PR TITLE
Cu 86b0rh5hn front end netlify ethan freire

### PR DESCRIPTION
**Pull request by ethanfreire**
the netlify link: https://boisterous-cassata-effa74.netlify.app/

The app is able to the home, login, register pages. The app is able to navigate through the tv series, movies, bookmark pages.

### CODE REVIEW

**Comment by allantito** [comment]
Task linked: [CU-86b0rh5hn Front end: Netlify](https://app.clickup.com/t/86b0rh5hn)

**Comment by ryanRATM** [comment]
@ethanfreire can you verify your page routes/links on the page work properly?

I tried creating an account and see the following network requests when i click the "Create Account" button
image

**Comment by ethanfreire** [comment]
> @ethanfreire can you verify your page routes/links on the page work properly?
> 
> I tried creating an account and see the following network requests when i click the "Create Account" button image

**Comment by ethanfreire** [comment]
@ryanRATM So guelmis made some updates to the backend code. So now we are able to login to the application. Although the backend service takes a while to get started. So after a delay of about 1 min the application will return a  network response of POST 200 OK and login the user and be redirected to the home page.

**Pull request merged**
